### ISSUE TITLE
Building with gradle fails

### ISSUE THREAD

**Issue by penguinized** [eseifert/gral#123]
When I try to build the library or the tests, it fails. Gradle complains about the build failing with an exception:

>$gradle assemble 
>
>FAILURE: Build failed with an exception.
>
>* Where:
>Build file '/home/user/Downloads/gral/gral/build.gradle' line: 93
>
>* What went wrong:
>A problem occurred evaluating root project 'GRAL'.
>> Could not find method jcenter() for arguments [] on repository container.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more >log output.
>
>BUILD FAILED
>

>Total time: 1.518 secs

Used Gradle version:
>$ gradle --version
>
>------------------------------------------------------------
>Gradle 1.5
>------------------------------------------------------------
>
>Gradle build time: Sonntag, 15. Juni 2014 15:27 Uhr UTC
>Groovy: 1.8.6
>Ant: Apache Ant(TM) version 1.9.4 compiled on May 9 2014
>Ivy: non official version
>JVM: 1.7.0_79 (Oracle Corporation 24.79-b02)
>OS: Linux 3.16.0-38-generic amd64

I am using Ubuntu 14.10 as OS, but the build failed in Windows 7, too.

Stacktrace from gradle:

     Exception is:
    org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'GRAL'.
            at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
            at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:116)
            at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
            at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:44)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:464)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
            at org.gradle.configuration.DefaultBuildConfigurer$ConfigureProject.execute(DefaultBuildConfigurer.java:38)
            at org.gradle.configuration.DefaultBuildConfigurer$ConfigureProject.execute(DefaultBuildConfigurer.java:36)
            at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:440)
            at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:435)
            at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:32)
            at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
            at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
            at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
            at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
            at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:39)
            at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:25)
            at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
            at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
            at org.gradle.launcher.Main.doAction(Main.java:48)
            at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
            at org.gradle.launcher.Main.main(Main.java:39)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
            at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
    Caused by: org.gradle.api.internal.MissingMethodException: Could not find method jcenter() for arguments [] on repository container.
            at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
            at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
            at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
            at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler_Decorated.invokeMethod(Unknown Source)
            at build_2hoobnco380v2iuu5rn8lrcpkc$_run_closure1_closure2.doCall(/home/christoph-scherer/Downloads/gral/gral/build.gradle:93)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:113)
            at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:76)
            at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositoryContainer.java:44)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:50)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
            at org.gradle.api.internal.initialization.AbstractScriptHandler.repositories(AbstractScriptHandler.java:66)
            at build_2hoobnco380v2iuu5rn8lrcpkc$_run_closure1.doCall(/home/christoph-scherer/Downloads/gral/gral/build.gradle:90)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
            at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
            at org.gradle.api.internal.project.AbstractProject.buildscript(AbstractProject.java:893)
            at org.gradle.api.Project$buildscript.call(Unknown Source)
            at org.gradle.api.internal.project.ProjectScript.buildscript(ProjectScript.groovy:42)
            at org.gradle.api.Script$buildscript.callCurrent(Unknown Source)
            at build_2hoobnco380v2iuu5rn8lrcpkc.run(/home/christoph-scherer/Downloads/gral/gral/build.gradle:89)
            at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
            ... 30 more

**Comment by seifertm** [comment]
Hello!

Thanks for the report.

From what I can tell, Gradle 1.5 does not have "jcentral()" defined.

The best solution would probably be to upgrade Gradle to a more recent version.
If this is not possible, try this:
Replace `jcentral()` in line 93 of `build.gradle` with `maven { url 'http://jcenter.bintray.com' }`

In case this does not work either, replace `jcentral()` with `mavenCentral()`

Maven Central was replaced in our Gradle build with JCentral, which contains more artifacts in Maven Central.

**Comment by penguinized** [comment]
Thankyou for your fast response. Using a more up-to-date version of Gradle (2.4, installed from a ppa https://launchpad.net/~cwchien/+archive/ubuntu/gradle) removes this problem. I wonder why Ubuntu and the Gradle plug-in developers for both Netbeans and Eclipse use an old version of Gradle...

But still, the build fails, because of some tests failing:  AbstractAxisRenderer2DTest. testSerialization  fails in line 95, according to the test summary. Is there a way to tell Gradle to create jar files nevertheless?

**Comment by seifertm** [comment]
Ah, sorry...
Yes, the test fails and you are already the second or third one to run into this issue (see #122). I am currently working on API changes in a separate branch, but *really* need to fix this.

To run the `build` task, but skip the `test` task in gradle, run `gradle build -x test`. This is also configurable in Eclipse. I don't know about Netbeans, though.

**Comment by penguinized** [comment]
ok, thankyou very much :smiley:

**Comment by seifertm** [comment]
You're welcome.

Tests should run now after you pulled the update.
