### ISSUE TITLE
In a headless linux environment svg fails

### ISSUE THREAD

**Issue by bonron** [eseifert/gral#181]
An `IllegalArgumentException` is thrown with the following stack trace:

> java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at de.erichseifert.gral.io.plots.DrawableWriterFactory.get(SourceFile:81)
> ...(My API stack)...
> Caused by: java.lang.IllegalArgumentException: Unsupported file format: image/svg+xml
> at de.erichseifert.gral.io.plots.VectorWriter.<init>(SourceFile:132)
> ... 38 more
> java.lang.IllegalArgumentException: Unsupported MIME type: image/svg+xml
> at de.erichseifert.gral.io.plots.DrawableWriterFactory.get(SourceFile:104)
> ...(My API stack)...

the message from the Exception is :
> Unsupported MIME type: image/svg+xml

To reproduce use a headless server or docker image _(make sure it is actually headless)_

This is how I used the writer (note that it works perfectly fine on windows):
`   try {`
`      DrawableWriter writer = DrawableWriterFactory.getInstance().get("image/svg+xml");`
`      writer.write(plot, outputStream, 1450, 538);`
`    } catch (IOException e) {`
`      e.printStackTrace();`
`    }`

**Comment by bonron** [comment]
This is likely related to issue https://github.com/eseifert/gral/issues/145

**Comment by eseifert** [comment]
Thanks for reporting this. I’ll have a look into it as soon as I can.

**Comment by eseifert** [comment]
Thanks for the report, and sorry it took this long.

The cause was not the headless environment: VectorGraphics2D was missing from the classpath there. In 0.11 `VectorWriter` only registered a format if the library was found, so an absent VectorGraphics2D showed up as "Unsupported MIME type".

Since 0.12 VectorGraphics2D is a declared runtime dependency, and if it is absent anyway, writing fails with `No VectorGraphics2D implementation found in any of the packages: [...]`. I verified both on a headless JVM.

Closing as resolved.
